#!/bin/bash

export MPI_DIR=/opt/intel/oneapi/mpi/2021.10.0
source ${MPI_DIR}/env/vars.sh

export I_MPI_OFFLOAD=2
export I_MPI_OFFLOAD_TOPOLIB=level_zero
export I_MPI_OFI_PROVIDER=shm
export I_MPI_HYDRA_BOOTSTRAP=ssh

export GNU_DIR=${LBPM_DEPS_DIR}/gnu-11.3.0
export LIBRARY_PATH=${GNU_DIR}/lib:${GNU_DIR}/lib64:$LIBRARY_PATH

export CUDA_DIR=${LBPM_DEPS_DIR}/cuda-11.8
export PATH=${CUDA_DIR}/bin:$PATH
export LD_LIBRARY_PATH=${CUDA_DIR}/lib64:$LD_LIBRARY_PATH

export LBPM_ZLIB_DIR=${LBPM_DEPS_DIR}/zlib_1.2.13
export LBPM_HDF5_DIR=${LBPM_DEPS_DIR}/hdf5_1.14.1
export LBPM_SILO_DIR=${LBPM_DEPS_DIR}/silo_4.11

export LD_LIBRARY_PATH=${LBPM_ZLIB_DIR}/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=${LBPM_HDF5_DIR}/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=${LBPM_SILO_DIR}/lib:$LD_LIBRARY_PATH

export LIBRARY_PATH=${LBPM_ZLIB_DIR}/lib:$LIBRARY_PATH
export LIBRARY_PATH=${LBPM_HDF5_DIR}/lib:$LIBRARY_PATH
export LIBRARY_PATH=${LBPM_SILO_DIR}/lib:$LIBRARY_PATH

export CPATH=${LBPM_ZLIB_DIR}/include:$CPATH
export CPATH=${LBPM_HDF5_DIR}/include:$CPATH
export CPATH=${LBPM_SILO_DIR}/include:$CPATH

